version: "3.8"

services:
  postgres:
    container_name: smart-manager-db
    # For prodution is recomendly use bitnami images
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: SM-DB
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
