name: Unit tests 

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of repositories
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: "npm"
          cache-dependency-path: "**"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test