name: Unit tests 

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of repositories
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "JWT_PRIVATE_kEY=${{ secrets.JWT_PRIVATE_kEY }}" >> .env
          echo "JWT_PUBLIC_KEY=${{ secrets.JWT_PUBLIC_KEY }}" >> .env
          echo "JWT_USER_ACCESS_EXPIRES_IN=${{ secrets.JWT_USER_ACCESS_EXPIRES_IN }}" >> .env
          echo "JWT_USER_REFRESH_EXPIRES_IN=${{ secrets.JWT_USER_REFRESH_EXPIRES_IN }}" >> .env
          echo "JWT_ADM_ACCESS_EXPIRES_IN=${{ secrets.JWT_ADM_ACCESS_EXPIRES_IN }}" >> .env
          echo "JWT_ADM_REFRESH_EXPIRES_IN=${{ secrets.JWT_ADM_REFRESH_EXPIRES_IN }}" >> .env
          echo "ADM_REFRESH_EXPIRES_IN=${{ secrets.ADM_REFRESH_EXPIRES_IN }}" >> .env
          echo "USER_REFRESH_EXPIRES_IN=${{ secrets.USER_REFRESH_EXPIRES_IN }}" >> .env

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test